CREATE TABLE IF NOT EXISTS "user"
(
    user_id     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    telegram_id BIGINT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS person
(
    person_id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT,
    firstname   VARCHAR NOT NULL,
    middlename  VARCHAR,
    lastname    VARCHAR NOT NULL,
    birth_day   INT     NOT NULL,
    birth_month INT     NOT NULL,
    birth_year  INT,
    FOREIGN KEY (user_id) REFERENCES "user"
);
